export const termekekLISTA = [
  {
    nev: "Hordó alakú macskabútor",
    kep: "kepek/butor1.png",
    kategoria: "Bútor",
    szin: "fekete",
    méret: "M",
    ar: 12995,
  },
  {
    nev: "Macskabútor",
    kep: "kepek/butor2.png",
    kategoria: "Bútor",
    szin: "bézs",
    méret: "S",
    ar: 12995,
  },
  {
    nev: "Ablakra akasztható fekhely",
    kep: "kepek/butor3.png",
    kategoria: "Bútor",
    szin: "szürke",
    méret: "L",
    ar: 12995,
  },
  {
    nev: "Macska mászóka",
    kep: "kepek/butor4.png",
    kategoria: "Bútor",
    szin: "fekete",
    méret: "L",
    ar: 12995,
  },
  {
    nev: "Kaktusz alakú kaparófa",
    kep: "kepek/butor5.png",
    kategoria: "Bútor",
    szin: "bézs",
    méret: "M",
    ar: 12995,
  },
  {
    nev: "Macska fekhely",
    kep: "kepek/butor6.png",
    kategoria: "Bútor",
    szin: "szürke",
    méret: "S",
    ar: 12995,
  },
  {
    nev: "Rugós macskajáték (4db)",
    kep: "kepek/jatek1.png",
    kategoria: "Játék",
    szin: "többszínű",
    méret: "S",
    ar: 1295,
  },
  {
    nev: "Tollas játékbot",
    kep: "kepek/jatek2.png",
    kategoria: "Játék",
    szin: "rózsaszín",
    méret: "M",
    ar: 1495,
  },
  {
    nev: "Egér macskajáték",
    kep: "kepek/jatek3.png",
    kategoria: "Játék",
    szin: "szürke",
    méret: "S",
    ar: 995,
  },
  {
    nev: "Tollas játékbot",
    kep: "kepek/jatek4.png",
    kategoria: "Játék",
    szin: "sárga",
    méret: "M",
    ar: 1295,
  },
  {
    nev: "Színes labdák (4db)",
    kep: "kepek/jatek5.png",
    kategoria: "Játék",
    szin: "többszínű",
    méret: "S",
    ar: 1095,
  },
  {
    nev: "Jutalomfalatos labdajáték",
    kep: "kepek/jatek6.png",
    kategoria: "Játék",
    szin: "piros",
    méret: "s",
    ar: 995,
  },
  {
    nev: "Mintás nyakörv",
    kep: "kepek/nyakorv1.png",
    kategoria: "Nyakörv",
    szin: "kék",
    méret: "S",
    ar: 1495,
  },
  {
    nev: "Nyakörv csengővel",
    kep: "kepek/nyakorv2.png",
    kategoria: "Nyakörv",
    szin: "szürke",
    méret: "M",
    ar: 1295,
  },
  {
    nev: "Virágos nyakörv",
    kep: "kepek/nyakorv3.png",
    kategoria: "Nyakörv",
    szin: "kék",
    méret: "S",
    ar: 1395,
  },
  {
    nev: "Macskahám",
    kep: "kepek/nyakorv4.png",
    kategoria: "Nyakörv",
    szin: "rózsaszín",
    méret: "L",
    ar: 1895,
  },
  {
    nev: "Egyszerű nyakörv",
    kep: "kepek/nyakorv5.png",
    kategoria: "Nyakörv",
    szin: "bézs",
    méret: "S",
    ar: 1295,
  },
  {
    nev: "Egyszerű nyakörv",
    kep: "kepek/nyakorv6.png",
    kategoria: "Nyakörv",
    szin: "kék",
    méret: "M",
    ar: 1695,
  },
  {
    nev: "Öntisztító macskaalom",
    kep: "kepek/alom1.png",
    kategoria: "Alom",
    szin: "szürke",
    méret: "L",
    ar: 12995,
  },
  {
    nev: "Zárt macskaalom",
    kep: "kepek/alom2.png",
    kategoria: "Alom",
    szin: "fekete",
    méret: "M",
    ar: 12995,
  },
  {
    nev: "Öntisztító macskaalom",
    kep: "kepek/alom3.png",
    kategoria: "Alom",
    szin: "fehér",
    méret: "L",
    ar: 12995,
  },
  {
    nev: "Zárt macskaalom",
    kep: "kepek/alom4.png",
    kategoria: "Alom",
    szin: "szürke",
    méret: "L",
    ar: 12995,
  },
  {
    nev: "Öntisztító macskaalom",
    kep: "kepek/alom5.png",
    kategoria: "Alom",
    szin: "fehér",
    méret: "M",
    ar: 12995,
  },
  {
    nev: "Zárt macskaalom",
    kep: "kepek/alom6.png",
    kategoria: "Alom",
    szin: "fehér",
    méret: "M",
    ar: 12995,
  },
];
